// Sample Data
import 'main.dart';
import 'observation_model.dart';

List<Observation> data = [
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.teen,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.male,
    ageGroup: AgeGroup.teen,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.senior,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.male,
    ageGroup: AgeGroup.teen,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.teen,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.senior,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.teen,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.senior,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.teen,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.senior,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.male,
    ageGroup: AgeGroup.teen,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.teen,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.senior,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.teen,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.senior,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.female,
    ageGroup: AgeGroup.adult,
    distance: Distance.within5ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.male,
    ageGroup: AgeGroup.teen,
    distance: Distance.moreThan10ft,
  ),
  Observation(
    holdingType: HoldingType.partialHold,
    gender: Gender.male,
    ageGroup: AgeGroup.senior,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.fullHold,
    gender: Gender.male,
    ageGroup: AgeGroup.adult,
    distance: Distance.between5And10ft,
  ),
  Observation(
    holdingType: HoldingType.noHold,
    gender: Gender.female,
    ageGroup: AgeGroup.teen,
    distance: Distance.within5ft,
  ),
];
